const pc_names = [
    "Vyre",
    "Aenys",
    "Lizel",
    "Gavatreau",
    "Clodayre",
    "Abidan",
    "Khoursa",
    "Mikesh",
    "Elysia",
    "Choreas",
    "Audrine",
    "Laimyra",
    "Grogunn",
    "Prystellian",
    "Eura",
    "Mikkeala",
    "Standinos",
    "Wycke",
    "Kinasta",
    "Esma",
    "Ejax",
    "Kallirokus",
    "Meopre",
    "Hersperon",
    "Samara",
    "Vyron",
    "Luvox",
    "Hespera",
    "Falko",
    "Dula",
    "Murie",
    "Salsquira",
    "Adah",
    "Cowper",
    "Dyvid",
    "Muntt",
    "Melana",
    "Staux",
    "Ecriane",
    "Xerith",
    "Juscott",
    "Laeris",
    "Ephirinik",
    "Michael",
    "Pyricles"
];

const pc_surnames = [
    "Zylor",
    "Latrial",
    "Tyrmox",
    "Fiel",
    "Tayne",
    "Bandor",
    "Varick",
    "Owlery",
    "Druddeon",
    "Sandre",
    "Wynrae",
    "Grugg",
    "von Smet",
    "Reyrex",
    "Batari",
    "Inawyns",
    "Daelth",
    "du Vale",
    "Ralex",
    "Cajyre",
    "Bramwell",
    "Rilunaeth",
    "Lafay",
    "Petry",
    "Yacline",
    "Aezuma",
    "Shangeiros",
    "Romoro",
    "Klegg",
    "Omarzo",
    "du Pyro",
    "Stymish",
    "Brynne",
    "Gallavan",
    "Thepiros",
    "Habella",
    "Quan",
    "Tayris",
    "Eleri",
    "Joleth",
    "Wingaard",
    "Horith",
    "Yosalr",
    "Mineret",
    "Kaveron",
    "Jackson",
    "Bryel"
];

const pc_jobs = [
    "Cashier",
    "Food preparation worker",
    "Stocking associate",
    "Laborer",
    "Janitor",
    "Construction worker",
    "Bookkeeper",
    "Medical assistant",
    "Bartender",
    "Administrative assistant",
    "Marketing specialist",
    "Police officer",
    "Electrician",
    "Mechanic",
    "Retail sales associate",
    "Carpenter",
    "Operations manager",
    "Line supervisor",
    "Truck Driver",
    "Nurse",
    "Software developer",
    "Lawyer"
];

const pc_email = [
    "gmail.com",
    "fer.as.com",
    "poem.com",
    "email.com",
    "brock.eu.com",
    "wty.com"
]