import { MainOptionsComponent } from "./components/main-options.js";
import { AppComponent } from "./components/app-component.js";
import { AppIcon } from "./components/app-icon.js";
import { MainScreenComponent } from "./components/main-screen.js";
import { MainBar } from "./components/main-bar.js";
import { AppInfo } from "./components/app-info.js";
import { StickyNote } from "./components/sticky-note.js";
import { LoginScreen } from "./components/login-screen.js";
import { PhoneComponent } from "./components/phone-component.js";
import { PhoneAppComponent } from "./components/phone-app-component.js";
import { BiosComponent } from "./components/bios-component.js";
import { MessageComponent } from "./components/message-component.js";
import { PhoneAppIcon } from "./components/phone-app-icon.js";
import { SiteComponent } from "./components/site-component.js";
import { UsbComponent } from "./components/usb-component.js";
import { UsbPort } from "./components/usb-port.js";
AppComponent;
AppIcon;
AppInfo;
BiosComponent;
LoginScreen;
MainBar;
MainOptionsComponent;
MainScreenComponent;
MessageComponent;
PhoneAppComponent;
PhoneAppIcon;
PhoneComponent;
SiteComponent;
StickyNote;
UsbComponent;
UsbPort;
